[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "epoch-boundary"
  total_instances = 4
  builder = "exec:go"
  runner = "local:exec"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "0"
  miners = "3"
  genesis_timestamp_offset = "0"
  balance = "20000000.5" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "mock"
  mining_mode = "synchronized"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

[[groups]]
  id = "attacker"
  [groups.build]

   # Implementation of the attacker.
   [[groups.build.dependencies]]
        module = "github.com/filecoin-project/lotus"
        target = "github.com/adlrocha/lotus"
        version = "b9ca4b71bf613ef9a1f21f302238c0d1fc55e65d"

   # Modification of gossipsub 
   [[groups.build.dependencies]]
        module = "github.com/libp2p/go-libp2p-pubsub"
        target = "github.com/adlrocha/go-libp2p-pubsub"
        version = "781f60ae88e4bcb79226232832e0a9b5a08dd3ed"

  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "miner"

# [[groups]]
#   id = "clients"
#   [groups.instances]
#     count = 0
#     percentage = 0.0
#   [groups.run]
#     [groups.run.test_params]
#       role = "client"
