name: lotus-filecoin
base: core20
version: latest
summary: filecoin daemon/client
description: |
  Filecoin is a peer-to-peer network that stores files on the internet
  with built-in economic incentives to ensure files are stored reliably over time
grade: devel
confinement: strict

parts:
  lotus:
    plugin: make
    source: ./
    build-snaps:
      - go
      - rustup
    build-packages:
      - git
      - jq
      - libhwloc-dev
      - ocl-icd-opencl-dev
      - pkg-config
    stage-packages:
      - libhwloc15
      - ocl-icd-libopencl1
    override-build: |
      LDFLAGS="" make lotus lotus-miner lotus-worker
      cp lotus lotus-miner lotus-worker $SNAPCRAFT_PART_INSTALL

layout:
  /var/tmp:
    symlink: $SNAP_DATA/var/tmp
apps:
  lotus:
    command: lotus
    plugs:
      - network
      - network-bind
  lotus-miner:
    command: lotus-miner
    plugs:
      - network
      - network-bind
      - opengl
  lotus-worker:
    command: lotus-worker
    plugs:
      - network
      - network-bind
      - opengl
